version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: word-of-wisdom-server:latest
    container_name: word-of-wisdom-server
    ports:
      - "8090:8080"
    environment:
      - ENV=dev
      - APP_ADDR=0.0.0.0:8080
    networks:
      - word_of_wisdom_network

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: word-of-wisdom-client:latest
    container_name: word-of-wisdom-client
    depends_on:
      - server
    environment:
      - ENV=dev
      - APP_SERVERADDR=server:8080
      - APP_RPS=1
    networks:
      - word_of_wisdom_network

networks:
  word_of_wisdom_network:
    driver: bridge